services:
  db:
    image: mysql:latest  
    environment:
      MYSQL_ROOT_PASSWORD: passwordtest
      MYSQL_DATABASE: test_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db  
    ports:
      - "5000:5000"  

volumes:
  db_data:
